name: Kotlin Multiplatform Tests
on: [push]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linuxX64Test
          - os: windows-latest
            target: mingwX64Test
          - os: macos-latest
            target: macosArm64Test
          - os: ubuntu-latest
            target: jsTest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Node.js
        if: matrix.target == 'jsTest'
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run get request tests
        shell: bash
        run: |
          ./gradlew ${{ matrix.target }} --tests "work.socialhub.khttpclient.GetTest.testSimpleGetSimple"

      - name: Upload get test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: get-test-results-${{ matrix.target }}
          path: build/reports/tests/
